# Generated by Django 4.2.7 on 2023-11-22 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articulos", "0002_comentario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comentario",
            old_name="Articulo",
            new_name="articulo",
        ),
    ]
