# Generated by Django 4.2.7 on 2023-11-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articulos", "0003_rename_articulo_comentario_articulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
