# Generated by Django 4.2.7 on 2023-11-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articulos", "0004_articulo_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="costo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
