# Generated by Django 4.2.7 on 2023-11-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articulos", "0005_articulo_costo"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="categoria",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
