# Generated by Django 4.2 on 2023-11-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_articulo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tracklist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='genero',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
