# Generated by Django 4.2 on 2023-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_remove_articulo_fecha_creacion_articulo_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
